### ISSUE TITLE
capstone import is directory dependent, causing library import errors

### ISSUE THREAD

**Issue by E3V3A** [aquynh/capstone#1269]
Ok, this really seem to be a persistent and unresolved issue, since the same issue appears all over the place.

The error we're talking about is: 
**`ImportError: ERROR: fail to load the dynamic library.`**

---

![firefox_2018-10-20_22-16-18](https://user-images.githubusercontent.com/194392/47259759-cda69300-d49d-11e8-91eb-320865473c9d.png)

---

To install I used: `pip3 install capstone`.
This worked just fine, and most stuff seem to run. At least the imports works...except:

I just noticed that the error seem to occur only when trying to use `import capstone` in a **sub-directory of `$HOME`**! 

```bash
# cd /anywhere

$ python3
Python 3.6.4 (default, Jan  7 2018, 15:53:53)
[GCC 6.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import capstone
>>> from capstone import *
>>> dir()
['CS_API_MAJOR', 'CS_API_MINOR', 'CS_ARCH_ALL', 'CS_ARCH_ARM', 'CS_ARCH_ARM64', 'CS_ARCH_MIPS', 'CS_ARCH_PPC', 'CS_ARCH_SPARC', 'CS_ARCH_SYSZ', 'CS_ARCH_X86', 'CS_ARCH_XCORE', 'CS_ERR_ARCH', 'CS_ERR_CSH', 'CS_ERR_DETAIL', 'CS_ERR_DIET', 'CS_ERR_HANDLE', 'CS_ERR_MEM', 'CS_ERR_MEMSETUP', 'CS_ERR_MODE', 'CS_ERR_OK', 'CS_ERR_OPTION', 'CS_ERR_SKIPDATA', 'CS_ERR_VERSION', 'CS_ERR_X86_ATT', 'CS_ERR_X86_INTEL', 'CS_GRP_CALL', 'CS_GRP_INT', 'CS_GRP_INVALID', 'CS_GRP_IRET', 'CS_GRP_JUMP', 'CS_GRP_RET', 'CS_MODE_16', 'CS_MODE_32', 'CS_MODE_64', 'CS_MODE_ARM', 'CS_MODE_BIG_ENDIAN', 'CS_MODE_LITTLE_ENDIAN', 'CS_MODE_MCLASS', 'CS_MODE_MICRO', 'CS_MODE_MIPS3', 'CS_MODE_MIPS32', 'CS_MODE_MIPS32R6', 'CS_MODE_MIPS64', 'CS_MODE_MIPSGP64', 'CS_MODE_THUMB', 'CS_MODE_V8', 'CS_MODE_V9', 'CS_OPT_DETAIL', 'CS_OPT_MODE', 'CS_OPT_OFF', 'CS_OPT_ON', 'CS_OPT_SYNTAX', 'CS_OPT_SYNTAX_ATT', 'CS_OPT_SYNTAX_DEFAULT', 'CS_OPT_SYNTAX_INTEL', 'CS_OPT_SYNTAX_NOREGNAME', 'CS_OP_FP', 'CS_OP_IMM', 'CS_OP_INVALID', 'CS_OP_MEM', 'CS_OP_REG', 'CS_SKIPDATA_CALLBACK', 'CS_SUPPORT_DIET', 'CS_SUPPORT_X86_REDUCE', 'CS_VERSION_EXTRA', 'CS_VERSION_MAJOR', 'CS_VERSION_MINOR', 'Cs', 'CsError', 'CsInsn', '__annotations__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'capstone', 'cs_disasm_lite', 'cs_disasm_quick', 'cs_support', 'cs_version', 'debug', 'version_bind']
>>>
```

However: 
```bash
# cd $HOME/capstone/bindings/python

$ python3
Python 3.6.4 (default, Jan  7 2018, 15:53:53)
[GCC 6.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import capstone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/capstone/bindings/python/capstone/__init__.py", line 315, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
>>>
```

WTF!?  :scream:  !  :skull_and_crossbones:  

Any ideas how to resolve?

**Comment by E3V3A** [comment]
@rhelmot
Any ideas?

**Comment by rhelmot** [comment]
You should add some print logging to the code at the top of capstone.py which attempts to locate the dynamic library to see where it’s looking and why it misses the location that it finds in other places.

**Comment by E3V3A** [comment]
This issue has been resolved by following this [updated installation procedure](https://github.com/aquynh/capstone/issues/1273),
when using **`Cygwin`** and **`Python3`**. 
A new [Wiki page](https://github.com/aquynh/capstone/wiki/Installing-on-Cygwin-&-Python3) has been added, describing the procedure.
