### ISSUE TITLE
AttributeError: regs_access

### ISSUE THREAD

**Issue by E3V3A** [aquynh/capstone#1270]
Running test script:

```bash
#  python3 -tt test_arm64.py
****************
Platform: ARM-64
Code: 0x09 0x00 0x38 0xd5 0xbf 0x40 0x00 0xd5 0x0c 0x05 0x13 0xd5 0x20 0x50 0x02 0x0e 0x20 0xe4 0x3d 0x0f 0x00 0x18 0xa0 0x5f 0xa2 0x00 0xae 0x9e 0x9f 0x37 0x03 0xd5 0xbf 0x33 0x03 0xd5 0xdf 0x3f 0x03 0xd5 0x21 0x7c 0x02 0x9b 0x21 0x7c 0x00 0x53 0x00 0x40 0x21 0x4b 0xe1 0x0b 0x40 0xb9 0x20 0x04 0x81 0xda 0x20 0x08 0x02 0x8b 0x10 0x5b 0xe8 0x3c
Disasm:
0x2c:   mrs     x9, midr_el1
        op_count: 2
                operands[0].type: REG = x9
                operands[1].type: REG_MRS = 0xc000
Traceback (most recent call last):
  File "test_arm64.py", line 130, in <module>
    test_class()
  File "test_arm64.py", line 122, in test_class
    print_insn_detail(insn)
  File "test_arm64.py", line 94, in print_insn_detail
    (regs_read, regs_write) = insn.regs_access()
  File "/usr/lib/python3.6/site-packages/capstone/__init__.py", line 586, in __getattr__
    raise AttributeError(name)
AttributeError: regs_access
```

**Comment by E3V3A** [comment]
seem like `insn.regs_access()` and `access()` are not supported here...

**Comment by E3V3A** [comment]
This issue has been resolved by following this [updated installation procedure](https://github.com/aquynh/capstone/issues/1273),
when using **`Cygwin`** and **`Python3`**. 
A new [Wiki page](https://github.com/aquynh/capstone/wiki/Installing-on-Cygwin-&-Python3) has been added, describing the procedure.
