### ISSUE TITLE
Can not use capstone in python

### ISSUE THREAD

**Issue by purinhow7** [aquynh/capstone#1646]
OS: Ubuntu 18.04
I tired to run the example on office site:

> from capstone import *
> 
> CODE = b"\x55\x48\x8b\x05\xb8\x13\x00\x00"
> 
> md = Cs(CS_ARCH_X86, CS_MODE_64)
> for i in md.disasm(CODE, 0x1000):
>     print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

However, python3 told me 

> Traceback (most recent call last):
>   File "capstone.py", line 1, in <module>
>     from capstone import *
>   File "/home/purin/Desktop/advunix_hw4/capstone.py", line 5, in <module>
>     md = Cs(CS_ARCH_X86, CS_MODE_64)
> NameError: name 'Cs' is not defined

I already installed capstone with pip3, pip

> purin@workubun:~$ pip3 install capstone                                                       
> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of 
> pip.                                                                                          
> Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue. 
> To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.    
> Defaulting to user installation because normal site-packages is not writeable                 
> Requirement already satisfied: capstone in ./.local/lib/python3.6/site-packages (4.0.2)

I also tried reinstall capstone. It is not helpful.
Is there any solution can help me use capstone on Python?

**Comment by purinhow7** [comment]
Filename (capstone) of the python script confuse python.
After change the filename, the script can run now.
