### ISSUE TITLE
Error in cs_disasm_quick due to missing attr on _dummy_cs

### ISSUE THREAD

**Issue by aidanhs** [aquynh/capstone#251]
```
>>> import capstone
>>> capstone.cs_disasm_quick(capstone.CS_ARCH_X86, capstone.CS_MODE_64, "\x55\x48\x8b\x05\xb8\x13\x00\x00", 0).next()
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "[...]\python\App\lib\site-packages\capstone\__init__.py", line 341, in cs_disasm_quick
    yield CsInsn(_dummy_cs(csh, arch), all_insn[i])
  File "[...]\python\App\lib\site-packages\capstone\__init__.py", line 410, in __init__
    if self._cs._detail:
AttributeError: '_dummy_cs' object has no attribute '_detail'
```

I guess _dummy_cs should set `_detail = False`.

**Comment by aquynh** [comment]
yes, that sounds right. would you mind sending in a pull request to fix that?

thanks.
