### ISSUE TITLE
undefined symbol: cs_reg_access

### ISSUE THREAD

**Issue by joxeankoret** [aquynh/capstone#308]
Hi!

Using the 'next' branch I noticed the following problem using the Python bindings by just running the test_x86.py example script:

```
$ python test_x86.py 
Traceback (most recent call last):
  File "test_x86.py", line 5, in <module>
    from capstone import *
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 310, in <module>
    _setup_prototype(_cs, "cs_regs_access", ctypes.c_int, ctypes.c_size_t, ctypes.POINTER(_cs_insn), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8), ctypes.POINTER(ctypes.c_uint16*64), ctypes.POINTER(ctypes.c_uint8))
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 292, in _setup_prototype
    getattr(lib, fname).restype = restype
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libcapstone.so.3: undefined symbol: cs_regs_access
```

Am I doing something wrong?

**Comment by joxeankoret** [comment]
Meeh... It was my fault: I had both this and the previous version of libcapstone installed. Sorry!

**Comment by aquynh** [comment]
this is because you did not install the core of `next` branch.

to be safe, be sure to always reinstall the core & bindings (if needed) whenever you pull the new code.

    sudo ./make.sh install
    cd bindings/python
    sudo make install
