### ISSUE TITLE
NPD at X86IntelInstPrinter.c:302

### ISSUE THREAD

**Issue by felixgr** [aquynh/capstone#393]
Reproduced on a34fc3a79db6c7d4e6014f275287a441090bb5f4 (branch "next") with CAPSTONE_USE_SYS_DYN_MEM and AddressSanitizer.

Also see fuzzing harness:
https://gist.github.com/felixgr/21ed36aed630978668aa

Side note: can you provide a build target in make.sh which provides a uniform debugging build with ASAN enabled?

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004fdc0d in get_op_access (h=<optimized out>, id=<optimized out>,
    access=0x7fffffffc3f0 "\003\001", eflags=<optimized out>)
    at src/arch/X86/X86IntelInstPrinter.c:302
302             for(i = 0; arr[i]; i++) {
(gdb) info locals
arr = 0x0
i = 0 '\000'
```

The null pointer dereference (NPD) occurs at line 302. In line 298, X86_get_op_access returns NULL. This is due to a deref at (*cache)[id] in insn_find returning NULL.

```
#0  insn_find (insns=<optimized out>, max=8484, id=2432, cache=0x6100000079b8)
    at src/utils.c:38
#1  0x00000000004f9af2 in X86_get_op_access (h=<optimized out>, id=2432, eflags=0x61c00002b100)
    at src/arch/X86/X86Mapping.c:3147
#2  0x00000000004fdbe1 in get_op_access (h=0x1bf6e60 <insns>, id=8484, access=0x7fffffffc3f0 "\003\001",
    eflags=0x980) at src/arch/X86/X86IntelInstPrinter.c:298
#3  0x00000000004fc05f in X86_Intel_printInst (MI=0x7fffffffc500, O=<optimized out>, Info=<optimized out>)
    at src/arch/X86/X86IntelInstPrinter.c:611
```

**Comment by felixgr** [comment]
```
printf "\\x00\\xFF\\x00\\xFF\\x00\\x10\\x00\\x00\\xAC\\x43\\xED\\x7F\\xFF\\x59\\xB5\\xFF\\x20\\xFF\\xFF\\x12\\x02\\xEC\\xAC\\xFA\\xAC\\xA1\\xC0\\xAC\\xB5\\x10\\x00\\xF3\\xA0\\x80\\xB1\\x00\\xAC\\x43\\xED\\x7F\\xFF\\xAC\\xB5\\xFF\\x20\\xFF\\xFF\\x12\\x02\\xEC\\xAC\\xFA\\xAC\\x89\\xC0\\xAC\\xB5\\x43\\x42\\xED\\x7F\\xFF\\xAC\\xB5\\xFF\\x02\\xEC\\xAC\\xFA\\xAC\\xAC\\xAC\\x00\\xEC\\x43\\xAB\\xAC\\xC5\\x3A\\x19\\xF3\\xF3\\xF3\\xF3\\x43\\x43\\x01\\xF8\\xEC\\x43\\x43\\x01\\xF8\\xCB\\xAC\\x40\\xED\\x7F\\xFF\\xAC\\xB5\\xFF\\x20\\xFF\\xFF\\x02\\x02\\xEC\\xAC\\xFA\\xAC\\xAC\\xAC\\x00\\xEC\\x43\\xAB\\xAC\\xC5\\x3A\\x19\\xF3\\xF3\\xF3\\xF3" > testcase
```

**Comment by aquynh** [comment]
thanks for these reports! a quick answer for the below question:

>  Side note: can you provide a build target in make.sh which provides a uniform debugging build with ASAN enabled?

please feel free to send a pull request to add the feature you want to `make.sh`, i will merge it.

**Comment by aquynh** [comment]
this bug was fixed with the commit https://github.com/aquynh/capstone/commit/0e9da8736a809f342f1210be38b01b5bc2da4d96, please confirm.

**Comment by felixgr** [comment]
Thanks for the fix. Verified.
