### ISSUE TITLE
OOB read size 4 in MipsDisassembler.c:1715

### ISSUE THREAD

**Issue by felixgr** [aquynh/capstone#394]
Reproduced on a34fc3a (branch "next") with CAPSTONE_USE_SYS_DYN_MEM and AddressSanitizer.

Also see fuzzing harness:
https://gist.github.com/felixgr/21ed36aed630978668aa

```
$ echo '0000000: 647a 5601 4023 d5d5 efcc d5d5            dzV.@#......' | xxd -r > testcase

#0  DecodeRegListOperand (Inst=<optimized out>, Insn=<optimized out>, Address=0, Decoder=<optimized out>)
    at src/arch/Mips/MipsDisassembler.c:1715
#1  0x000000000055728e in DecodeMemMMImm12 (Inst=<optimized out>, Insn=<optimized out>, Address=0,
    Decoder=<optimized out>) at src/arch/Mips/MipsDisassembler.c:1218


==10796==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000015cb9c0 at pc 0x00000055891d bp 0
x7fffffffc1e0 sp 0x7fffffffc1d8
READ of size 4 at 0x0000015cb9c0 thread T0
    #0 0x55891c in DecodeRegListOperand src/arch/Mips/MipsDisassembler.c:1715:30
    #1 0x55728d in DecodeMemMMImm12 src/arch/Mips/MipsDisassembler.c:1218:8
    #2 0x551e67 in decodeToMCInst src/arch/Mips/MipsGenDisassemblerTables.inc:6941:1
    #3 0x5509cd in decodeInstruction src/arch/Mips/MipsGenDisassemblerTables.inc:6942:1
    #4 0x55017e in MipsDisassembler_getInstruction src/arch/Mips/MipsDisassembler.c:440
:12
    #5 0x54fcad in Mips_getInstruction src/arch/Mips/MipsDisassembler.c:509:24
    #6 0x4eb74e in cs_disasm src/cs.c:570:7

0x0000015cb9c0 is located 0 bytes to the right of global variable 'DecodeRegListOperand.Regs' defined in 'src/arch/Mips/MipsDisassembler.c' (0x15cb9a0) of size 32
SUMMARY: AddressSanitizer: global-buffer-overflow src/arch/Mips/MipsDisassembler.c:1715
:30 in DecodeRegListOperand
Shadow bytes around the buggy address:
  0x0000802b16e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802b16f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802b1700: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802b1710: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802b1720: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 f9 f9
=>0x0000802b1730: f9 f9 f9 f9 00 00 00 00[f9]f9 f9 f9 00 00 00 00
  0x0000802b1740: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000802b1750: 00 00 00 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x0000802b1760: 05 f9 f9 f9 f9 f9 f9 f9 00 02 f9 f9 f9 f9 f9 f9
  0x0000802b1770: 05 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9 f9 f9 f9 f9
  0x0000802b1780: 07 f9 f9 f9 f9 f9 f9 f9 06 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10796==ABORTING
```

Anything I can do to help debugging?

**Comment by aquynh** [comment]
yes, because the output above is a bit confused, so please provide the hex input triggering the problem (is it `647a 5601 4023 d5d5 efcc d5d5` ?) & the exact mode (i dont see this info anywhere), so i can reproduce that with on my side with my own script (sorry i am busy so have not setup AddressSanitizer yet to run your fuzzy).

thanks

**Comment by aquynh** [comment]
can you confirm now the "next" branch with this commit https://github.com/aquynh/capstone/commit/c009dc6dbff9cfd484192d622347eb5d3539f973 fixes your issue?

thanks.

**Comment by felixgr** [comment]
Yes, that was the input.

Thanks for the fix. Verified.
