### ISSUE TITLE
fail to load the dynamic library

### ISSUE THREAD

**Issue by hdarwin** [aquynh/capstone#469]
```
root@localhost:~# pip install --upgrade capstone
Requirement already up-to-date: capstone in /usr/local/lib/python2.7/dist-packages
root@localhost:~# python -c "import capstone"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```
how can i solve thie problem?

**Comment by hdarwin** [comment]
I don't know what happend on my system. but i solved problem.
```
root@localhost:/usr/lib/python2.7/dist-packages# cd /usr/lib/python2.7/dist-packages
root@localhost:/usr/lib/python2.7/dist-packages# mkdir capstone
root@localhost:/usr/lib/python2.7/dist-packages# cd capstone
root@localhost:/usr/lib/python2.7/dist-packages/capstone# cp /usr/local/lib/python2.7/dist-packages/usr/lib/python2.7/dist-packages/capstone/libcapstone.so ./
root@localhost:/usr/lib/python2.7/dist-packages/capstone# python -c 'import capstone'
```
