### ISSUE TITLE
setup.py absent from archive

### ISSUE THREAD

**Issue by r1git** [aquynh/capstone#896]
Hello,

Download `https://github.com/aquynh/capstone/archive/next.zip#subdirectory=bindings/python`
Unzip
There is no setup.py

Is that normal behavior ?

(Found from building pwndbg project: https://github.com/pwndbg/pwndbg which rely on this download)

**Comment by zachriggle** [comment]
@r1git misunderstands how `pip`'s `requirements.txt` works, this is not an issue.

```
$ pip uninstall -y capstone &>/dev/null
$ echo 'https://github.com/aquynh/capstone/archive/next.zip#subdirectory=bindings/python' > requirements.txt
$ pip install -Ur requirements.txt
Collecting https://github.com/aquynh/capstone/archive/next.zip#subdirectory=bindings/python (from -r requirements.txt (line 1))
  Downloading https://github.com/aquynh/capstone/archive/next.zip (3.5MB)
...
Installing collected packages: capstone
  Running setup.py install for capstone ... done
Successfully installed capstone-4.0.0rc1
```

**Comment by r1git** [comment]
@zachriggle Here is what I get with the same commands as you:
```
[...]
$ pip install -Ur requirements.txt
Downloading/unpacking https://github.com/aquynh/capstone/archive/next.zip (from -r requirements.txt (line 1))
  Downloading next.zip (unknown size): 3.5MB downloaded
  Running setup.py (path:/tmp/pip-Ta8odN-build/setup.py) egg_info for package from https://github.com/aquynh/capstone/archive/next.zip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-Ta8odN-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-Ta8odN-build/setup.py'
```
Hence my remark about setup.py not present in the zip file: pip complains about it being not there.

**Comment by r1git** [comment]
The faulty system was a mess. Resigned and re-installed from scratch. Problem solved.
:-/
