### ISSUE TITLE
Python 3 : failed to load dynamic library

### ISSUE THREAD

**Issue by Wenzel** [aquynh/capstone#961]
Hi !

I tried to install the capstone library on Python3, and it fails to load the capstone C library:

~~~Python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
~~~

A `Dockerfile` to reproduce the issue:
~~~Dockerfile
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
        git \
        python3 \
        python3-pip

RUN pip3 install capstone

ENTRYPOINT python3 -c 'import capstone'
~~~

-> So does Python Capstone supports Python 3 ?

**Comment by Rot127** [comment]
Works since our CI uses Python3
